---

version: '3'
services:
  deploy:
    image: automium/service-kubernetes
    container_name: automium-service-kubernetes
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file:
      - ${CONFIG:-.env}
    network_mode: host
