---

apiVersion: v1
kind: Service
metadata:
  name: automium-cluster-autoscaler-svc
  namespace: kube-system
  labels:
    automium-component: cluster-autoscaler
spec:
  ports:
    - port: 8085
      protocol: TCP
  clusterIP: None
  selector:
    automium-component: cluster-autoscaler
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: automium-cluster-autoscaler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      automium-component: cluster-autoscaler
  serviceName: automium-cluster-autoscaler-svc
  template:
    metadata:
      labels:
        automium-component: cluster-autoscaler
    spec:
      containers:
        - name: cluster-autoscaler
          image: automium/cluster-autoscaler:master
          imagePullPolicy: Always
          args:
            - --logtostderr
            - -v=5
            - --cloud-provider=automium
            - --cloud-config=/etc/automium/autoscaler/config/config.yaml
            - --kubeconfig=/etc/automium/autoscaler/kubeconfigs/cluster-kubeconfig
          volumeMounts:
            - name: config
              mountPath: /etc/automium/autoscaler/config
              readOnly: true
            - name: kubeconfigs
              mountPath: /etc/automium/autoscaler/kubeconfigs
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: automium-cluster-autoscaler-config
        - name: kubeconfigs
          secret:
            secretName: automium-cluster-autoscaler-kubeconfigs
