---

- name: configure-others | create Inventory From Consul
  command: "/usr/src/cloud/consul_io.py"
  register: command_output

- name: configure-others | preset variables for others nodes
  set_fact:
    cluster_name: "{{ cluster_name }}"
    dynamic_inventory_from_consul: "{{ command_output.stdout |from_json }}"
    etcd_name: "{{ cluster_name }}-etcd"
    kube_master_name: "{{ cluster_name }}-kube-master"
    kube_node_name: "{{ cluster_name }}-kube-node"

- name: configure-others | preset variables for others nodes
  set_fact:
    etcd_name_up: "{{ etcd_name }}_up"
    kube_master_name_up: "{{ kube_master_name }}_up"
    kube_node_name_up: "{{ kube_node_name }}_up"

- name: configure-others | print etcd_name kube_master_name kube_node_name
  debug:
    msg: "{{ etcd_name }} - {{kube_master_name}} - {{ kube_node_name }}"

- name: configure-others | print etcd_name_up kube_master_name_up kube_node_name_up
  debug:
    msg: "{{ kube_node_name_up }} - {{ kube_master_name_up }} - {{ etcd_name_up }}"

- name: configure-others | create list of Host in Cluster ( select host witch name {{cluster_name}} )
  set_fact:
    render_host_list_all: |
      {%- for host in dynamic_inventory_from_consul.all %}
      {% if cluster_name in dynamic_inventory_from_consul._meta.hostvars[host].consul_nodename %}
      - {{host}}
      {% endif %}
      {% endfor %}

- name: configure-others | configure Variables cluster_host_list_all host_list_etcd host_list_kube_master host_list_kube_node
  set_fact:
    this_node: "{{ ansible_default_ipv4['address'] |string }}"
    cluster_host_list_all: "{{render_host_list_all | from_yaml }}"
    host_list_etcd: "{{ dynamic_inventory_from_consul[etcd_name] |default('') }}"
    host_list_kube_master: "{{ dynamic_inventory_from_consul[kube_master_name] | default('') }}"
    host_list_kube_node: "{{ dynamic_inventory_from_consul[kube_node_name] | default('') }}"

- name: configure-others | configure Variables cluster_host_list_all host_list_etcd host_list_kube_master host_list_kube_node
  set_fact:
    host_list_etcd_up: "{{ dynamic_inventory_from_consul[etcd_name_up] |default('') }}"
    host_list_kube_master_up: "{{ dynamic_inventory_from_consul[kube_master_name_up] | default('') }}"
    host_list_kube_node_up: "{{ dynamic_inventory_from_consul[kube_node_name_up] | default('') }}"

- name: configure-others | configure variables etcd_master ( etcd + master host list deduplicated )
  set_fact:
    etcd_master: "{{ host_list_etcd | union( host_list_kube_master ) }}"

- name: configure-others | set this node + etcd + master
  set_fact:
    etcd_master_this_node: "{{ [this_node] + etcd_master }}"

- name: configure-others | show var dynamic_inventory_from_consul
  debug:
    var: dynamic_inventory_from_consul

- name: configure-others | show var cluster_host_list_all
  debug:
    var: cluster_host_list_all

- name: configure-others | show var host_list_etcd
  debug:
    var: host_list_etcd

- name: configure-others | show var host_list_kube_master
  debug:
    var: host_list_kube_master

- name: configure-others | show var host_list_kube_node
  debug:
    var: host_list_kube_node

- name: configure-others | show var host_list_etcd_up
  debug:
    var: host_list_etcd_up

- name: configure-others | show var host_list_kube_master_up
  debug:
    var: host_list_kube_master_up

- name: configure-others | show var host_list_kube_node_up
  debug:
    var: host_list_kube_node_up

- name: configure-bootstrap | show var etcd_master
  debug:
    var: etcd_master

- name: configure-bootstrap | show var etcd_master_this_node
  debug:
    var: etcd_master_this_node

- name: configure-others | render dinamic inventory
  set_fact:
    dynamic_invertory: |
      [all]
      {% if ansible_default_ipv4['address'] in etcd_master_this_node %}
      {{ dynamic_inventory_from_consul._meta.hostvars[ansible_default_ipv4['address']].consul_nodename }} ansible_host={{ansible_default_ipv4['address']}} etcd_member_name={{ dynamic_inventory_from_consul._meta.hostvars[ansible_default_ipv4['address']].consul_nodename }}
      {% endif %}
      {% for host in cluster_host_list_all %}
      {% if host != ansible_default_ipv4['address'] %}
      {{ dynamic_inventory_from_consul._meta.hostvars[host].consul_nodename }} ansible_host={{host}} etcd_member_name={{ dynamic_inventory_from_consul._meta.hostvars[host].consul_nodename }}
      {% endif %}
      {% endfor %}

      [etcd]
      {% if ansible_default_ipv4['address'] in host_list_etcd  %}
      {{ dynamic_inventory_from_consul._meta.hostvars[ansible_default_ipv4['address']].consul_nodename }} ansible_host={{ansible_default_ipv4['address']}}
      {% endif %}
      {% for host in host_list_etcd_up %}
      {% if host != ansible_default_ipv4['address'] %}
      {{ dynamic_inventory_from_consul._meta.hostvars[host].consul_nodename }} ansible_host={{host}}
      {% endif %}
      {% endfor %}

      [kube-master]
      {% if ansible_default_ipv4['address'] in host_list_kube_master %}
      {{ dynamic_inventory_from_consul._meta.hostvars[ansible_default_ipv4['address']].consul_nodename }} ansible_host={{ansible_default_ipv4['address']}}
      {% endif %}
      {% for host in host_list_kube_master_up %}
      {% if host != ansible_default_ipv4['address'] %}
      {{ dynamic_inventory_from_consul._meta.hostvars[host].consul_nodename }} ansible_host={{host}}
      {% endif %}
      {% endfor %}

      [kube-node]
      {% if ansible_default_ipv4['address'] in host_list_kube_node %}
      {{ dynamic_inventory_from_consul._meta.hostvars[ansible_default_ipv4['address']].consul_nodename }} ansible_host={{ansible_default_ipv4['address']}}
      {% endif %}

      [k8s-cluster:children]
      kube-master
      kube-node
