---

- name: enable-autoscaler | start autoscaling after the deployment
  shell: |
    ssh -o StrictHostKeyChecking=no root@{{ cluster_name }}-kube-master.service.automium.consul kubectl -n kube-system scale --replicas=1 statefulset automium-cluster-autoscaler
